version: '3'

services:
  node1:
    build: ./DbNode
    container_name: node1
    restart: always
    ports:
     - "9002:9000"
    networks:
      custom_network:
        ipv4_address: 192.168.1.101

  node2:
    build: ./DbNode
    container_name: node2
    restart: always
    ports:
     - "9003:9000"
    networks:
      custom_network:
        ipv4_address: 192.168.1.102

  node3:
    build: ./DbNode
    container_name: node3
    restart: always
    ports:
     - "9004:9000"
    networks:
      custom_network:
        ipv4_address: 192.168.1.103

  node4:
    build: ./DbNode
    container_name: node4
    restart: always
    ports:
     - "9005:9000"
    networks:
      custom_network:
        ipv4_address: 192.168.1.104

  bootstrapper:
    build: ./Bootstrapper
    container_name: bootstrapper
    restart: always
    ports:
      - "8082:8080"
    networks:
      custom_network:
        ipv4_address: 192.168.1.6
    depends_on:
      - node1
      - node2
      - node3
      - node4

  taskapp:
    build: ./TaskAssignmentApp
    container_name: taskapp
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - bootstrapper
    networks:
      custom_network:
        ipv4_address: 192.168.1.106

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
